### ISSUE TITLE
V3 Plugins not installing

### ISSUE THREAD

**Issue by causefx** [Tobotimus/Tobo-Cogs#33]
I also had this issue with Jumperman, he said:

```
Fixed. I forgot to update to comply with the new standard in Red.
```

Here is the error:

```
[05/10/2018 23:26] ERROR core_commands _load 98: Package loading failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/redbot/core/core_commands.py", line 96, in _load
    await bot.load_extension(spec)
  File "/usr/local/lib/python3.6/dist-packages/redbot/core/bot.py", line 230, in load_extension
    lib.setup(self)
  File "/data/cogs/CogManager/cogs/reactkarma/__init__.py", line 27, in setup
    bot.add_cog(ReactKarma())
  File "/usr/local/lib/python3.6/dist-packages/redbot/core/bot.py", line 387, in add_cog
    f"The {cog.__class__.__name__} cog in the {cog.__module__} package does "
RuntimeError: The ReactKarma cog in the reactkarma.reactkarma package does not inherit from the commands.Cog base class. The cog author must update the cog to adhere to this requirement.
```

**Comment by Tobotimus** [comment]
Thanks for your report @causefx :smiley:
Fixed in deb9fdd.
