### ISSUE TITLE
[streamroles] 403 Forbidden

### ISSUE THREAD

**Issue by JayC1337** [Tobotimus/Tobo-Cogs#69]
Trying to configure whitelist for streamrole, which gives me the following error:

```py
[2020-06-28 16:59:58] [ERROR] red: Exception in command 'streamrole setmode'
Traceback (most recent call last):
  File "/home/jayc/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 83, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/jayc/.local/share/Red-DiscordBot/data/gamaraza/cogs/CogManager/cogs/streamroles/streamroles.py", line 83, in setmode
    await self._update_guild(ctx.guild)
  File "/home/jayc/.local/share/Red-DiscordBot/data/gamaraza/cogs/CogManager/cogs/streamroles/streamroles.py", line 433, in _update_guild
    await self._update_member(member, streamer_role, alerts_channel)
  File "/home/jayc/.local/share/Red-DiscordBot/data/gamaraza/cogs/CogManager/cogs/streamroles/streamroles.py", line 389, in _update_member
    await member.add_roles(role)
  File "/home/jayc/redenv/lib/python3.8/site-packages/discord/member.py", line 641, in add_roles
    await req(guild_id, user_id, role.id, reason=reason)
  File "/home/jayc/redenv/lib/python3.8/site-packages/discord/http.py", line 221, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions
```

Bot has Administrator Permissions (8).

**Comment by Tobotimus** [comment]
Even if your bot has administrator permissions, it cannot do anything with roles which are above it in the hierarchy. I'm guessing that's what's happening here.

In the Roles section of your Server Settings, drag the bot's role higher than the streamrole. Please let me know if this doesn't fix your issue. Closing for now.
