### ISSUE TITLE
[Streamroles] Not updated for Prsence intent

### ISSUE THREAD

**Issue by scarecr0w12** [Tobotimus/Tobo-Cogs#83]
This cog is not updated properly for member updates:

```
Ignoring exception in on_member_update
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/home/container/.local/share/Red-DiscordBot/data/pterodactyl/cogs/CogManager/cogs/streamroles/streamroles.py", line 464, in on_member_update
    await self._update_member(after)
  File "/home/container/.local/share/Red-DiscordBot/data/pterodactyl/cogs/CogManager/cogs/streamroles/streamroles.py", line 371, in _update_member
    await member.remove_roles(role)
  File "/home/container/.local/lib/python3.8/site-packages/discord/member.py", line 822, in remove_roles
    await req(guild_id, user_id, role.id, reason=reason)
  File "/home/container/.local/lib/python3.8/site-packages/discord/http.py", line 248, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions
[04:36:47] ERROR    [red.streamroles] Error whilst loading streamroles:
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /home/container/.local/share/Red-DiscordBot/data/pterodactyl/cogs/CogManager │
│ /cogs/streamroles/__init__.py:12 in setup                                    │
│ ❱ 12         await cog.initialize()                                          │
│ /home/container/.local/share/Red-DiscordBot/data/pterodactyl/cogs/CogManager │
│ /cogs/streamroles/streamroles.py:49 in initialize                            │
│ ❱  49             await self._update_guild(guild)                            │
│ /home/container/.local/share/Red-DiscordBot/data/pterodactyl/cogs/CogManager │
│ /cogs/streamroles/streamroles.py:408 in _update_guild                        │
│ ❱ 408             await self._update_member(member, streamer_role, alerts_ch │
│ /home/container/.local/share/Red-DiscordBot/data/pterodactyl/cogs/CogManager │
│ /cogs/streamroles/streamroles.py:371 in _update_member                       │
│ ❱ 371             await member.remove_roles(role)                            │
│ /home/container/.local/lib/python3.8/site-packages/discord/member.py:822 in  │
│ remove_roles                                                                 │
│ ❱ 822                 await req(guild_id, user_id, role.id, reason=reason)   │
│ /home/container/.local/lib/python3.8/site-packages/discord/http.py:248 in    │
│ request                                                                      │
│ ❱  248                             raise Forbidden(r, data)                  │
╰──────────────────────────────────────────────────────────────────────────────╯
Forbidden: 403 Forbidden (error code: 50013): Missing Permissions
           ERROR    [red] Package loading failed
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /home/container/.local/lib/python3.8/site-packages/redbot/core/core_commands │
│ .py:172 in _load                                                             │
│ ❱  172                 await bot.load_extension(spec)                        │
│ /home/container/.local/lib/python3.8/site-packages/redbot/core/bot.py:1561   │
│ in load_extension                                                            │
│ ❱ 1561                 await lib.setup(self)                                 │
│ /home/container/.local/share/Red-DiscordBot/data/pterodactyl/cogs/CogManager │
│ /cogs/streamroles/__init__.py:12 in setup                                    │
│ ❱ 12         await cog.initialize()                                          │
│ /home/container/.local/share/Red-DiscordBot/data/pterodactyl/cogs/CogManager │
│ /cogs/streamroles/streamroles.py:49 in initialize                            │
│ ❱  49             await self._update_guild(guild)                            │
│ /home/container/.local/share/Red-DiscordBot/data/pterodactyl/cogs/CogManager │
│ /cogs/streamroles/streamroles.py:408 in _update_guild                        │
│ ❱ 408             await self._update_member(member, streamer_role, alerts_ch │
│ /home/container/.local/share/Red-DiscordBot/data/pterodactyl/cogs/CogManager │
│ /cogs/streamroles/streamroles.py:371 in _update_member                       │
│ ❱ 371             await member.remove_roles(role)                            │
│ /home/container/.local/lib/python3.8/site-packages/discord/member.py:822 in  │
│ remove_roles                                                                 │
│ ❱ 822                 await req(guild_id, user_id, role.id, reason=reason)   │
│ /home/container/.local/lib/python3.8/site-packages/discord/http.py:248 in    │
│ request                                                                      │
│ ❱  248                             raise Forbidden(r, data)                  │
╰──────────────────────────────────────────────────────────────────────────────╯
Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

```

**Comment by aikaterna** [comment]
Your bot doesn't have permission to remove roles in one of the Discord servers it's in. As an aside, Pterodactyl installs of Red are not generally supported.

**Comment by Tobotimus** [comment]
Yes, as aikaterna said, this is not to do with intents. Your bot needs permissions to assign roles to users for the cog to work.
